mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mappers/*Mapper.xml
  type-aliases-package: kr.co.rland.web.entity

spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 600MB
      max-request-size: 600MB
