spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://db.newlecture.com:3306/rlanddb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: rland
    password: 20231110

logging:
  level:
    kr:
      co:
        rland:
          web:
            repository: TRACE